### ISSUE TITLE
Database initialisation

### ISSUE THREAD

**Issue by ivank** [EasyGoingLove/Rps_Universe-With-React#1]
You can improve this to use [docker-compose](https://docs.docker.com/compose/)

```yaml
version: "3.9"

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: rpsdata
```

with the corresponding init script:

```sql
CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(255),
    password VARCHAR(255)
);
```

So that you can start the whole thing with

```shell
docker compose up
```

And have a running db with the correct database. Much easier to review
